name: fact-ai-rideshare
channels:
  - ibmdecisionoptimization
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=1.0.0
  - brotlipy=0.7.0
  - c-ares=1.18.1
  - ca-certificates=2021.10.8
  - certifi=2021.10.8
  - cffi=1.15.0
  - charset-normalizer=2.0.10
  - colorama=0.4.4
  - cplex=20.1
  - cryptography=36.0.1
  - cudatoolkit=11.6.0
  - cudnn=8.2.1.32
  - cycler=0.11.0
  - dataclasses=0.8
  - docplex=2.22.213
  - freetype=2.10.4
  - future=0.18.2
  - grpcio=1.43.0
  - icu=67.1
  - idna=3.3
  - importlib-metadata=4.10.1
  - joblib=1.1.0
  - kiwisolver=1.3.2
  - ld_impl_linux-64=2.36.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - liblapack=3.9.0
  - libnsl=2.0.0
  - libpng=1.6.37
  - libprotobuf=3.19.3
  - libstdcxx-ng=11.2.0
  - libzlib=1.2.11
  - llvm-openmp=12.0.1
  - magma=2.5.4
  - markdown=3.3.6
  - matplotlib=3.2.2
  - matplotlib-base=3.2.2
  - mkl=2022.0.1
  - nccl=2.11.4.1
  - ncurses=6.3
  - ninja=1.10.2
  - numpy=1.22.1
  - openssl=1.1.1l
  - pandas=1.4.0
  - pip=22.0.2
  - protobuf=3.19.3
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pyparsing=3.0.7
  - pysocks=1.7.1
  - python=3.8.12
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytorch=1.10.1
  - pytorch-gpu=1.10.1
  - pytorch-lightning=0.8.5
  - pytz=2021.3
  - pyyaml=6.0
  - readline=8.1
  - requests=2.27.1
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - setuptools=59.5.0
  - six=1.16.0
  - sleef=3.5.1
  - sqlite=3.37.0
  - tbb=2021.5.0
  - tensorboard=1.15.0
  - threadpoolctl=3.0.0
  - tk=8.6.11
  - tornado=6.1
  - tqdm=4.62.3
  - typing_extensions=4.0.1
  - urllib3=1.26.8
  - werkzeug=2.0.2
  - wheel=0.37.1
  - xz=5.2.5
  - yaml=0.2.5
  - zipp=3.7.0
  - zlib=1.2.11